version: "3"

services:
  node:
    build: .
    volumes:
      - .:/src
    ports:
    - '80:80'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./my-db:/var/lib/mysql